lab1
mmurze/OS_labs_2023 pull request #1
Opened 2023-10-27 15:50 UTC by mmurze

2023-10-27 23:16 UTC, DariaWelt requested changes
Не билдится:
```
root@Ubuntu:/home/vboxuser/os_labs/mmurze/lab1# sh build.sh 
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:7 (add_executable):
  Cannot find source file:

    src/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:7 (add_executable):
  No SOURCES given to target: daemon
```

2023-10-31 18:43 UTC, DariaWelt requested changes

2023-10-31 18:43 UTC, DariaWelt commented on lab1/config.cpp
> +std::vector<ConfigRow> Config::getRows() const { return mRows; }
У Вас происходит ненужное копирование mRows, а так как это происходит в рабочем цикле демона, необходимо оперировать ссылками:
```suggestion
const std::vector<ConfigRow>& Config::getRows() const { return mRows; }
```

2023-10-31 18:43 UTC, DariaWelt commented on lab1/daemon.cpp
> +    std::vector<ConfigRow> rows = mConfig.getRows();
```suggestion
   auto rows = mConfig.getRows();
```

2023-10-31 18:43 UTC, DariaWelt commented on lab1/daemon.cpp
> +Daemon::Daemon(const std::string &configPath) {
Чтобы избежать ненужных конструкторов по умолчанию:
```suggestion
Daemon::Daemon(const std::string &configPath)
: mPathToConfig(fs::absolute(configPath))
, mConfig(mPathToConfig){
```

2023-10-31 18:43 UTC, DariaWelt commented on lab1/config.h
> +  Config() = default;
От конструктора по умолчанию можно избавиться.

2023-10-31 18:43 UTC, DariaWelt commented on lab1/daemon.h
> +  Daemon(Daemon &&) = delete;
Оператор присваивания не запрещен

2023-10-31 18:43 UTC, DariaWelt commented on lab1/daemon.h
> +  static std::string mPathToConfig;
Почему эти поля статические, а остальные нет?

2023-10-31 18:43 UTC, DariaWelt commented on lab1/from/text.txt
папку from нужно убрать

2023-11-02 09:34 UTC, mmurze commented on lab1/daemon.h
> +  static std::string mPathToConfig;
поле конфига и путь до конфига используются в статическом методе handleSignals, поэтому тоже должны быть статическими

2023-11-03 20:37 UTC, DariaWelt approved these changes

2023-11-03 20:37 UTC, merged

2023-11-03 20:38 UTC, DariaWelt commented
@mmurze , Напишите свое ФИ, чтобы я проставила баллы